### ISSUE TITLE
Skipping DICOM to NIFTI Conversion

### ISSUE THREAD

**Issue by tjhendrickson** [beOn/hcpre#4]
Hi Ben,

Thanks for providing this package to the neuroimaging community. Currently the workflow that I have already has converted data in NIFTI format. Is there a way to manipulate the configuration in order to skip the DICOM path request?

-Tim

**Comment by beOn** [comment]
Sorry for the slow reply - been out with the flu for the past few days. Get the shot if you haven't already!

Skipping DICOMs will get a little hairy, but not too hairy... several parameters that get passed to the pipeline are pulled from the DICOM headers, so you'd have to supply those. This should be doable using the config mechanism, but there isn't at this point a way to use the config to skip the DICOM nodes altogether.

Though it might be redundant, your best option might be to just let hcpre re-convert the DICOMs (if you have access to them). It'll only take a second of compute time, and'll save you a bunch of futzing around with the code.

**Comment by tjhendrickson** [comment]
Not a problem, thanks for getting back to me. In hindsight I should have
looked more at the code before emailing you. Based on my data architecture
being different than the ones assumed within the config file generation I
think using the interfaces (pre-fs, vs, etc) is the most efficient path for
me. That doesn't require a config file right?

I hope to extend the interface capability by including  diffusion, rsfrmi,
and tfmri pipeline interfaces.

Tim

**Comment by beOn** [comment]
Right! There's no requirement that you use the config stuff if you're using the interfaces directly. If you run into trouble, it might help to take a look at the code that applies the stuff in the config file to the various interfaces.

Adding the other pipelines would be great!
