### ISSUE TITLE
PreFS interface problems

### ISSUE THREAD

**Issue by tjhendrickson** [beOn/hcpre#5]
Hi Ben,

I have made significant progress towards using hcpre in order to run the HCP processing stream on my data, however, I have run into problems. For whatever reason the PreFS interface has problems with some of the arguments that I place within PreFSInputSpec. For an example of the issue please see the screen-shot. In this screen shot I am showing that I have entered a path to a fnirt configuration file, however PreFS acts as if I did not enter information at all. Is there a particular format in which I should be entering files? What I have been doing is generating a string from a previously defined variable pointing to the top level HCP pipeline directory and concatenating with '+' to specific file locations. For example: with pre_fs = PreFSInputSpec I attempted to enter the following information pre_fs.fnirt_config = pipeline_dir + 'global/config/T1_2_MNI152_2mm.cnf'. 

Any thoughts?

![prefs_bug](https://user-images.githubusercontent.com/7429880/33394210-3783b1aa-d507-11e7-8e01-bd36a5945bce.png)

**Comment by beOn** [comment]
I presume there's a reason you're not just using the config file to do this, but if there isn't... just do that.

It's been a hot second since I touched nipype, but I believe the issue is that you're setting pre_fs.fnirt_config, and you need to be setting pre_fs.inputs.fnirt_config instead.

**Comment by tjhendrickson** [comment]
Hmm, I don't think that is the issue. pre_fs is set to PreFSInputSpec which is the same as the input object for PreFS (PreFS.input_spec). I might try manipulating the source code a little bit, I've noticed that the variables in which the following format is used fails: "InputMultiPath(File(".

**Comment by beOn** [comment]
Take a look at the other places where input values get set - the style is always X.input.Y (pretty sure). I used to get bit by this from time to time when working with nipype.

Before diving in, why not give .input a shot?

Ben

**Comment by tjhendrickson** [comment]
You're right. I'll give that a try first.

**Comment by tjhendrickson** [comment]
That worked. Good suggestion!

**Comment by beOn** [comment]
Great! I remember being flummoxed by the same issue myself… I won’t say how many times :P

**Comment by tjhendrickson** [comment]
What I find strange about that usage is that my IDE cannot find the sub objects (fnirt_config, t1, etc) as I would expect, so it feels incorrect
